import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'maarten' at '3/17/15 3:17 PM' with Gradle 2.3
 *
 * @author maarten, @date 3/17/15 3:17 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        TicTacToeApp classUnderTest = new TicTacToeApp();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
