import javafx.application.Application;
import javafx.stage.Stage;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'maarten' at '3/17/15 3:17 PM' with Gradle 2.3
 *
 * @author maarten, @date 3/17/15 3:17 PM
 */
public class TicTacToeApp extends Application {
		
		public static void main(String[] args) {
			launch(args);
		}

		@Override
		public void start(Stage primaryStage) throws Exception {
			
		}
}
